A few tweaks and improvements

diff --git a/git-release b/git-release
--- a/git-release
+++ b/git-release
@@ -1,26 +1,34 @@
 #!/bin/bash
 
-if [ "$1" != 'major' -a "$1" != 'minor' -a "$1" != 'patch' ]; then
-  >&2 echo "Usage: git release major|minor|patch"
+if [ "$1" != 'major' -a "$1" != 'minor' -a "$1" != 'patch' -a "$1" != 'init' ]; then
+  >&2 echo "Usage: git release major|minor|patch|init"
   exit 1
 fi
 
-if [ `git rev-parse master` != `git rev-parse origin/master` ]; then
-  echo "Error: master is out of date with origin, please update first!"
+if [ `git rev-parse master` != `git rev-parse origin/master 2> /dev/null` ]; then
+  >&2 echo "Error: master is out of date with origin, please update/push first!"
   exit 1
 fi
 
-lastVersion=`git describe --abbrev=0 master`
+lastVersion=`git describe --abbrev=0 master 2> /dev/null`
 
 if [ $? != 0 ]; then
-  read -p "No tags found in repo, shall we initialize this repo for gitflow? [y/N] " -n 1 -r
-  echo
-  if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
-    git flow init
-    lastVersion="0.0.0"
+  if [ "$1" == 'init' ]; then
+    read -p "No tags found in repo, shall we initialize this repo for gitflow? [Y/n] " -n 1 -r
+    echo
+    if echo $REPLY | grep -E '^[Nn]$' > /dev/null; then
+      exit 1
+    else
+      git flow init
+      lastVersion="0.0.0"
+    fi
   else
+    >&2 echo "Error: no tags found in repo, run again with 'init' to initialize for gitflow"
     exit 1
   fi
+elif [ `git rev-parse develop` != `git rev-parse origin/develop 2> /dev/null` ]; then
+  >&2 echo "Error: develop is out of date with origin, please update/push first!"
+  exit 1
 fi
 
 versionArray=(${lastVersion//./ })
@@ -34,13 +42,17 @@ elif [ "$1" == 'minor' ]; then
   newVersion="$major.$((minor+1)).0"
 elif [ "$1" == 'patch' ]; then
   newVersion="$major.$minor.$((patch+1))"
+elif [ "$1" == 'init' ]; then
+  newVersion="0.1.0"
 fi
 
 echo "Last release was version ${lastVersion}."
 echo "We're about to create a new $1 release, with version ${newVersion}."
-read -p "Continue? [y/N] " -n 1 -r
+read -p "Continue? [Y/n] " -n 1 -r
 echo
-if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
+if echo $REPLY | grep -E '^[Nn]$' > /dev/null; then
+  exit 1
+else
   if [ "$1" == 'patch' ]; then
     git flow hotfix start $newVersion
   else
